"""Make product seller required

Revision ID: f258c7855ef2
Revises: ddc8a5b27ea1
Create Date: 2026-09-25 21:59:34.004705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f258c7855ef2'
down_revision: Union[str, Sequence[str], None] = 'ddc8a5b27ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.alter_column('products', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
